// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package runner

import (
	"context"
	"sync"
)

// Ensure, that GitHubMock does implement GitHub.
// If this is not the case, regenerate this file with moq.
var _ GitHub = &GitHubMock{}

// GitHubMock is a mock implementation of GitHub.
//
//	func TestSomethingThatUsesGitHub(t *testing.T) {
//
//		// make and configure a mocked GitHub
//		mockedGitHub := &GitHubMock{
//			CommitsHTMLFunc: func(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool) {
//				panic("mock out the CommitsHTML method")
//			},
//			CountOpenBumpPRsFunc: func(ctx context.Context, base string) (int, error) {
//				panic("mock out the CountOpenBumpPRs method")
//			},
//			HasOpenPRWithPrefixFunc: func(ctx context.Context, base string, prefix string) (bool, error) {
//				panic("mock out the HasOpenPRWithPrefix method")
//			},
//			OpenBumpPRFunc: func(ctx context.Context, in BumpPRInput) (int, bool, error) {
//				panic("mock out the OpenBumpPR method")
//			},
//			ReadFileFunc: func(ctx context.Context, path string, ref string) ([]byte, string, error) {
//				panic("mock out the ReadFile method")
//			},
//			ReleaseNotesHTMLFunc: func(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool) {
//				panic("mock out the ReleaseNotesHTML method")
//			},
//		}
//
//		// use mockedGitHub in code that requires GitHub
//		// and then make assertions.
//
//	}
type GitHubMock struct {
	// CommitsHTMLFunc mocks the CommitsHTML method.
	CommitsHTMLFunc func(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool)

	// CountOpenBumpPRsFunc mocks the CountOpenBumpPRs method.
	CountOpenBumpPRsFunc func(ctx context.Context, base string) (int, error)

	// HasOpenPRWithPrefixFunc mocks the HasOpenPRWithPrefix method.
	HasOpenPRWithPrefixFunc func(ctx context.Context, base string, prefix string) (bool, error)

	// OpenBumpPRFunc mocks the OpenBumpPR method.
	OpenBumpPRFunc func(ctx context.Context, in BumpPRInput) (int, bool, error)

	// ReadFileFunc mocks the ReadFile method.
	ReadFileFunc func(ctx context.Context, path string, ref string) ([]byte, string, error)

	// ReleaseNotesHTMLFunc mocks the ReleaseNotesHTML method.
	ReleaseNotesHTMLFunc func(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool)

	// calls tracks calls to the methods.
	calls struct {
		// CommitsHTML holds details about calls to the CommitsHTML method.
		CommitsHTML []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// FromVersion is the fromVersion argument value.
			FromVersion string
			// ToVersion is the toVersion argument value.
			ToVersion string
		}
		// CountOpenBumpPRs holds details about calls to the CountOpenBumpPRs method.
		CountOpenBumpPRs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Base is the base argument value.
			Base string
		}
		// HasOpenPRWithPrefix holds details about calls to the HasOpenPRWithPrefix method.
		HasOpenPRWithPrefix []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Base is the base argument value.
			Base string
			// Prefix is the prefix argument value.
			Prefix string
		}
		// OpenBumpPR holds details about calls to the OpenBumpPR method.
		OpenBumpPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In BumpPRInput
		}
		// ReadFile holds details about calls to the ReadFile method.
		ReadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Ref is the ref argument value.
			Ref string
		}
		// ReleaseNotesHTML holds details about calls to the ReleaseNotesHTML method.
		ReleaseNotesHTML []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// FromVersion is the fromVersion argument value.
			FromVersion string
			// ToVersion is the toVersion argument value.
			ToVersion string
		}
	}
	lockCommitsHTML         sync.RWMutex
	lockCountOpenBumpPRs    sync.RWMutex
	lockHasOpenPRWithPrefix sync.RWMutex
	lockOpenBumpPR          sync.RWMutex
	lockReadFile            sync.RWMutex
	lockReleaseNotesHTML    sync.RWMutex
}

// CommitsHTML calls CommitsHTMLFunc.
func (mock *GitHubMock) CommitsHTML(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool) {
	if mock.CommitsHTMLFunc == nil {
		panic("GitHubMock.CommitsHTMLFunc: method is nil but GitHub.CommitsHTML was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Repo        string
		FromVersion string
		ToVersion   string
	}{
		Ctx:         ctx,
		Repo:        repo,
		FromVersion: fromVersion,
		ToVersion:   toVersion,
	}
	mock.lockCommitsHTML.Lock()
	mock.calls.CommitsHTML = append(mock.calls.CommitsHTML, callInfo)
	mock.lockCommitsHTML.Unlock()
	return mock.CommitsHTMLFunc(ctx, repo, fromVersion, toVersion)
}

// CommitsHTMLCalls gets all the calls that were made to CommitsHTML.
// Check the length with:
//
//	len(mockedGitHub.CommitsHTMLCalls())
func (mock *GitHubMock) CommitsHTMLCalls() []struct {
	Ctx         context.Context
	Repo        string
	FromVersion string
	ToVersion   string
} {
	var calls []struct {
		Ctx         context.Context
		Repo        string
		FromVersion string
		ToVersion   string
	}
	mock.lockCommitsHTML.RLock()
	calls = mock.calls.CommitsHTML
	mock.lockCommitsHTML.RUnlock()
	return calls
}

// CountOpenBumpPRs calls CountOpenBumpPRsFunc.
func (mock *GitHubMock) CountOpenBumpPRs(ctx context.Context, base string) (int, error) {
	if mock.CountOpenBumpPRsFunc == nil {
		panic("GitHubMock.CountOpenBumpPRsFunc: method is nil but GitHub.CountOpenBumpPRs was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Base string
	}{
		Ctx:  ctx,
		Base: base,
	}
	mock.lockCountOpenBumpPRs.Lock()
	mock.calls.CountOpenBumpPRs = append(mock.calls.CountOpenBumpPRs, callInfo)
	mock.lockCountOpenBumpPRs.Unlock()
	return mock.CountOpenBumpPRsFunc(ctx, base)
}

// CountOpenBumpPRsCalls gets all the calls that were made to CountOpenBumpPRs.
// Check the length with:
//
//	len(mockedGitHub.CountOpenBumpPRsCalls())
func (mock *GitHubMock) CountOpenBumpPRsCalls() []struct {
	Ctx  context.Context
	Base string
} {
	var calls []struct {
		Ctx  context.Context
		Base string
	}
	mock.lockCountOpenBumpPRs.RLock()
	calls = mock.calls.CountOpenBumpPRs
	mock.lockCountOpenBumpPRs.RUnlock()
	return calls
}

// HasOpenPRWithPrefix calls HasOpenPRWithPrefixFunc.
func (mock *GitHubMock) HasOpenPRWithPrefix(ctx context.Context, base string, prefix string) (bool, error) {
	if mock.HasOpenPRWithPrefixFunc == nil {
		panic("GitHubMock.HasOpenPRWithPrefixFunc: method is nil but GitHub.HasOpenPRWithPrefix was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Base   string
		Prefix string
	}{
		Ctx:    ctx,
		Base:   base,
		Prefix: prefix,
	}
	mock.lockHasOpenPRWithPrefix.Lock()
	mock.calls.HasOpenPRWithPrefix = append(mock.calls.HasOpenPRWithPrefix, callInfo)
	mock.lockHasOpenPRWithPrefix.Unlock()
	return mock.HasOpenPRWithPrefixFunc(ctx, base, prefix)
}

// HasOpenPRWithPrefixCalls gets all the calls that were made to HasOpenPRWithPrefix.
// Check the length with:
//
//	len(mockedGitHub.HasOpenPRWithPrefixCalls())
func (mock *GitHubMock) HasOpenPRWithPrefixCalls() []struct {
	Ctx    context.Context
	Base   string
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Base   string
		Prefix string
	}
	mock.lockHasOpenPRWithPrefix.RLock()
	calls = mock.calls.HasOpenPRWithPrefix
	mock.lockHasOpenPRWithPrefix.RUnlock()
	return calls
}

// OpenBumpPR calls OpenBumpPRFunc.
func (mock *GitHubMock) OpenBumpPR(ctx context.Context, in BumpPRInput) (int, bool, error) {
	if mock.OpenBumpPRFunc == nil {
		panic("GitHubMock.OpenBumpPRFunc: method is nil but GitHub.OpenBumpPR was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  BumpPRInput
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockOpenBumpPR.Lock()
	mock.calls.OpenBumpPR = append(mock.calls.OpenBumpPR, callInfo)
	mock.lockOpenBumpPR.Unlock()
	return mock.OpenBumpPRFunc(ctx, in)
}

// OpenBumpPRCalls gets all the calls that were made to OpenBumpPR.
// Check the length with:
//
//	len(mockedGitHub.OpenBumpPRCalls())
func (mock *GitHubMock) OpenBumpPRCalls() []struct {
	Ctx context.Context
	In  BumpPRInput
} {
	var calls []struct {
		Ctx context.Context
		In  BumpPRInput
	}
	mock.lockOpenBumpPR.RLock()
	calls = mock.calls.OpenBumpPR
	mock.lockOpenBumpPR.RUnlock()
	return calls
}

// ReadFile calls ReadFileFunc.
func (mock *GitHubMock) ReadFile(ctx context.Context, path string, ref string) ([]byte, string, error) {
	if mock.ReadFileFunc == nil {
		panic("GitHubMock.ReadFileFunc: method is nil but GitHub.ReadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Ref  string
	}{
		Ctx:  ctx,
		Path: path,
		Ref:  ref,
	}
	mock.lockReadFile.Lock()
	mock.calls.ReadFile = append(mock.calls.ReadFile, callInfo)
	mock.lockReadFile.Unlock()
	return mock.ReadFileFunc(ctx, path, ref)
}

// ReadFileCalls gets all the calls that were made to ReadFile.
// Check the length with:
//
//	len(mockedGitHub.ReadFileCalls())
func (mock *GitHubMock) ReadFileCalls() []struct {
	Ctx  context.Context
	Path string
	Ref  string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Ref  string
	}
	mock.lockReadFile.RLock()
	calls = mock.calls.ReadFile
	mock.lockReadFile.RUnlock()
	return calls
}

// ReleaseNotesHTML calls ReleaseNotesHTMLFunc.
func (mock *GitHubMock) ReleaseNotesHTML(ctx context.Context, repo string, fromVersion string, toVersion string) (string, bool) {
	if mock.ReleaseNotesHTMLFunc == nil {
		panic("GitHubMock.ReleaseNotesHTMLFunc: method is nil but GitHub.ReleaseNotesHTML was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Repo        string
		FromVersion string
		ToVersion   string
	}{
		Ctx:         ctx,
		Repo:        repo,
		FromVersion: fromVersion,
		ToVersion:   toVersion,
	}
	mock.lockReleaseNotesHTML.Lock()
	mock.calls.ReleaseNotesHTML = append(mock.calls.ReleaseNotesHTML, callInfo)
	mock.lockReleaseNotesHTML.Unlock()
	return mock.ReleaseNotesHTMLFunc(ctx, repo, fromVersion, toVersion)
}

// ReleaseNotesHTMLCalls gets all the calls that were made to ReleaseNotesHTML.
// Check the length with:
//
//	len(mockedGitHub.ReleaseNotesHTMLCalls())
func (mock *GitHubMock) ReleaseNotesHTMLCalls() []struct {
	Ctx         context.Context
	Repo        string
	FromVersion string
	ToVersion   string
} {
	var calls []struct {
		Ctx         context.Context
		Repo        string
		FromVersion string
		ToVersion   string
	}
	mock.lockReleaseNotesHTML.RLock()
	calls = mock.calls.ReleaseNotesHTML
	mock.lockReleaseNotesHTML.RUnlock()
	return calls
}
